In [1]:
import numpy as np

Dmh = np.random.randn(3,3)
Dmbh = np.random.randn(3,3)
Dsh = np.random.randn(2,2)
Dbh = np.random.randn(3,3)

print(Dmh)
print(Dmbh)
print(Dbh)
print(Dsh)

[[-0.35825387 -0.62718771  0.86709737]
 [-1.97469961  0.27482341 -1.13476399]
 [ 1.63767001 -0.0702419   1.06233118]]
[[-1.24511923  2.00073666 -1.45690591]
 [-0.06504605 -0.43739502  2.2083658 ]
 [-0.67233427  0.60375408  0.35541994]]
[[ 0.76669767  0.02781744  0.21982657]
 [-1.91843884  1.00324568  1.19941916]
 [-1.85183267 -0.65065249  0.79915126]]
[[-0.61098781 -0.61669903]
 [-0.30176179 -0.6554593 ]]


In [2]:
De_1 = np.hstack([Dmh,Dmbh,np.zeros((3, 2))])
De_2 = np.hstack([Dmbh,Dbh,np.zeros((3,2))])
De_3 = np.hstack([np.zeros((2,3)), np.zeros((2,3)), Dsh])
De = np.vstack([De_1, De_2, De_3])

print(De_1)
print(De_2)
print(De_3)
print(De)

[[-0.35825387 -0.62718771  0.86709737 -1.24511923  2.00073666 -1.45690591
   0.          0.        ]
 [-1.97469961  0.27482341 -1.13476399 -0.06504605 -0.43739502  2.2083658
   0.          0.        ]
 [ 1.63767001 -0.0702419   1.06233118 -0.67233427  0.60375408  0.35541994
   0.          0.        ]]
[[-1.24511923  2.00073666 -1.45690591  0.76669767  0.02781744  0.21982657
   0.          0.        ]
 [-0.06504605 -0.43739502  2.2083658  -1.91843884  1.00324568  1.19941916
   0.          0.        ]
 [-0.67233427  0.60375408  0.35541994 -1.85183267 -0.65065249  0.79915126
   0.          0.        ]]
[[ 0.          0.          0.          0.          0.          0.
  -0.61098781 -0.61669903]
 [ 0.          0.          0.          0.          0.          0.
  -0.30176179 -0.6554593 ]]
[[-0.35825387 -0.62718771  0.86709737 -1.24511923  2.00073666 -1.45690591
   0.          0.        ]
 [-1.97469961  0.27482341 -1.13476399 -0.06504605 -0.43739502  2.2083658
   0.          0.        ]
 [ 1.

In [3]:
De = np.array([[Dmh,            Dmbh,           np.zeros((3, 2))],
                [Dmbh,          Dbh,            np.zeros((3, 2))],
                [np.zeros((2,3)), np.zeros((2,3)), Dsh]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 3) + inhomogeneous part.